---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cluster-api
configurations:
- kustomize-config.yaml
resources:
- ../../base
- ../../components/core/v1.9.7
- ../../components/capmox/v0.7.1
- ../../components/in-cluster-ipam/v1.0.2
- sealed-secrets.yaml

secretGenerator:
- name: capmox-manager-credentials
  files:
  - ./sealed-secrets.yaml
  options:
    annotations:
      config.kubernetes.io/local-config: "true"

patches:
- patch: |-
    $patch: delete
    apiVersion: v1
    kind: Secret
    metadata:
      name: capmox-manager-credentials
  target:
    group: ""
    version: v1
    kind: Secret
    name: capmox-manager-credentials
- patch: |-
    - op: add
      path: /spec/template/metadata/labels/app.kubernetes.io~1part-of
      value: capi
  target:
    group: apps
    version: v1
    kind: Deployment
# Make Capmox Infra Provider's webhook cert have a unique name
- patch: |-
    - op: replace
      path: /spec/secretName
      value: capmox-webhook-server-cert
  target:
    group: cert-manager.io
    version: v1
    kind: Certificate
    name: capmox-serving-cert
- patch: |-
    - op: add
      path: /spec/template/spec/volumes/0/secret/secretName
      value: capmox-webhook-server-cert
  target:
    group: apps
    version: v1
    kind: Deployment
    name: capmox-controller-manager