---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-api
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - cluster: in-cluster
        overlay: mgmt
  template:
    metadata:
      name: "{{overlay}}-cluster-api"
      namespace: argocd
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: "{{overlay}}"
      ignoreDifferences: []
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - ApplyOutOfSyncOnly=true
        - ServerSideApply=true
      source:
        repoURL: https://github.com/Dayzpd/kustomize-cluster-api
        targetRevision: HEAD
        path: "overlays/{{overlay}}"
      destination:
        name: "{{cluster}}"
        namespace: cluster-api
